name: ${name}
version: ${version}
description: Blocks first-time players; only returning players may join.
api-version: 1.14
author: shikendon

main: io.github.phateio.preloginevent.PreLoginEvent

libraries:
  - com.maxmind.geoip:geoip-api:1.3.1
